function p = DependencyList
%DEPENDENCYLIST Additions to the search path defaults.
%   DEPENDENCYLIST returns a string that can be used as input to ADDPATH
%   in order to set the path.

global Settings
Dpath = Settings.DependenciesPath;
sep = ';';

d = Dependencies.Dependencies;

p = [ ...
%%% BEGIN ENTRIES %%%
cell2mat(cellfun(@(x) [Dpath x sep],...
    {d(find(cellfun(@isempty,{d.IncludeSubDirs}))).Name},...
    'UniformOutput',false)), ...
...
cell2mat(cellfun(@(x) genpath([Dpath x]),...
    {d(find(~cellfun(@isempty,{d.IncludeSubDirs}))).Name},...
    'UniformOutput',false)), ...
%%% END ENTRIES %%%
     ...
];


