function p = FolderExceptionList
%FOLDEREXCEPTIONLIST Exceptions to the search path folders from the dependency list.
%   FOLDEREXCEPTIONLIST returns a string that can be used as input to RMPATH

global Settings
Dpath = Settings.DependenciesPath;

p = [...
%%% BEGIN ENTRIES %%%
     genpath([Dpath 'amtoolbox\thirdparty\sfs\doc'        ]), ...
     genpath([Dpath 'amtoolbox\thirdparty\sfs\SFS_octave' ]), ...
     genpath([Dpath 'amtoolbox\thirdparty\src'            ]), ...
     genpath([Dpath 'SpeechSP_Tools\.git'                 ]), ...
%%% END ENTRIES %%%
     ...
];

