clear;clear classes;close all;fclose all;clc;

Zone_Weights = 1e4;
Zone_Weights_ = Zone_Weights;
Noise_Mask_Levels = [-40 -35 -30 -25 -20 -15 -10 -5 0 5 10 15 20];% 25 30 35 40];
Noise_Mask_Levels_ = Noise_Mask_Levels; %Backup variable
Leakage_Angle = 0;
array_type = 'circle';
if strcmp(array_type, 'circle')
    [x,y] = pol2cart(-90/180*pi, 0.6);
    x_ = sqrt(1.5^2-y^2);
    th_c = atan2(y,-x_);
    th = th_c;
elseif strcmp(array_type, 'line')
    x_=1.5;
    th_c = 180;
    th = atan2(-0.6,-1.5);
end
loudspeaker_layout = { ...
    'numberof_loudspeakers',        24, ...
    'loudspeaker_radius',           1.5, ...
    'loudspeaker_model',            'Genelec 8010A', ...
    'angleof_loudspeakerarrcentre', 180, ...
    'loudspeaker_spacing',          [], ...
    'speaker_array_type',           array_type };
other = { ...
    'resolution',                   100, ... % Minimum resolution of approx 50 for 8kHz signal to satisfy nyquist theorem. We choose 100 for good measure.
    'reproduction_radius',          1.0, ...
    'bright_weight',                1.0, ...
    'quiet_weight',                 0, ...
    'unattended_weight',            0.05, ...
    'brightzone_radius',            0.3, ...
    'brightzone_pos_distance',      0.6, ...
    'quietzone_radius',             0.3, ...
    'quietzone_pos_distance',       0.6, ...
    'maximum_frequency',            8000, ...
    'angleof_loudspeakerarc',       180, ...
    'angleof_loudspeakerarrcentre', 180, ...
    'loudspeaker_object',           Parametric_Synthesis.parametric_soundfield };

main_layout = {};
masker_layout = {};

%%
setups = [10, 10.1, 10.2, 10.3];
% setups = [ 10.1];
%setups = [0];

for scheme = setups
    if scheme == 0
        % % Setup and Privacy Scheme 0 (Benchmark)
        Zone_Weights = 0;
        Masker_Type = 'NoMask';
        main_layout = {'brightzone_pos_angle',        180, ...
                         'quietzone_pos_angle',         0, ...
                         'brightzone_source_angle',     0};
        Noise_Mask_Levels = -inf;
    elseif scheme == 1
        % % Setup and Privacy Scheme 1
        Masker_Type = 'FlatMask';
        main_layout = {'brightzone_pos_angle',        180, ...
                         'quietzone_pos_angle',         0, ...
                         'brightzone_source_angle',     0};
    elseif scheme == 2
        % % Setup and Privacy Scheme 2
        Masker_Type = 'ZoneWeightMask';
        main_layout = {'brightzone_pos_angle',        180, ...
                         'quietzone_pos_angle',         0, ...
                         'brightzone_source_angle',     0};
        masker_layout = {'brightzone_pos_angle',        0, ...
                         'quietzone_pos_angle',         180, ...
                         'brightzone_source_angle',     0};
    elseif scheme == 3
        % % Setup and Privacy Scheme 3
        Masker_Type = 'FlatMask';
        main_layout = {'brightzone_pos_angle',        180, ...
                         'quietzone_pos_angle',         0, ...
                         'brightzone_source_angle',     15};
    elseif scheme == 4
        % % Setup and Privacy Scheme 4
        Masker_Type = 'ZoneWeightMask';
        main_layout = {'brightzone_pos_angle',        180, ...
                         'quietzone_pos_angle',         0, ...
                         'brightzone_source_angle',     15};
        masker_layout = {'brightzone_pos_angle',        0, ...
                         'quietzone_pos_angle',         180, ...
                         'brightzone_source_angle',     0};
    elseif scheme == 5
        % % Setup and Privacy Scheme 5
        Masker_Type = 'FlatMask';
        main_layout = {'brightzone_pos_angle',        180, ...
                         'quietzone_pos_angle',         0, ...
                         'brightzone_source_angle',     90};
    elseif scheme == 6
        % % Setup and Privacy Scheme 6
        Masker_Type = 'ZoneWeightMask';
        main_layout = {'brightzone_pos_angle',        180, ...
                         'quietzone_pos_angle',         0, ...
                         'brightzone_source_angle',     90};
        masker_layout = {'brightzone_pos_angle',        0, ...
                         'quietzone_pos_angle',         180, ...
                         'brightzone_source_angle',     0};
        
    %Test Schemes    
    elseif scheme == 7
        % % Setup and Privacy Scheme 7
        Masker_Type = 'ZoneWeightMask_AliasCtrl';
        main_layout = {'brightzone_pos_angle',        180, ...
                         'quietzone_pos_angle',         0, ...
                         'brightzone_source_angle',     15};
        masker_layout = {'brightzone_pos_angle',        0, ...
                         'quietzone_pos_angle',         180, ...
                         'brightzone_source_angle',     0};
    elseif scheme == 7.5
        % % Setup and Privacy Scheme 7.5
        Masker_Type = 'ZoneWeightMask_AliasCtrl';
        main_layout = {'brightzone_pos_angle',        90, ...
                         'quietzone_pos_angle',         -90, ...
                         'brightzone_source_angle',     0};
        masker_layout = {'brightzone_pos_angle',        -90, ...
                         'quietzone_pos_angle',         90, ...
                         'brightzone_source_angle',     -60};
    elseif scheme == 7.6
        % % Setup and Privacy Scheme 7.6
        Masker_Type = 'ZoneWeightMask_AliasCtrl';
        main_layout = {'brightzone_pos_angle',        90, ...
                         'quietzone_pos_angle',         -90, ...
                         'brightzone_source_angle',     0};
        masker_layout = {'brightzone_pos_angle',        -90, ...
                         'quietzone_pos_angle',         90, ...
                         'brightzone_source_angle',     0};
    elseif scheme == 7.7
        % % Setup and Privacy Scheme 7.7
        Masker_Type = 'ZoneWeightMask_AliasCtrl';
        main_layout = {'brightzone_pos_angle',        90, ...
                         'quietzone_pos_angle',         -90, ...
                         'brightzone_source_angle',     0};
        masker_layout = {'brightzone_pos_angle',        -90, ...
                         'quietzone_pos_angle',         90, ...
                         'brightzone_source_angle',     -45};
    elseif scheme == 8
        % % Setup and Privacy Scheme 8
        Masker_Type = 'ZoneWeightMask_AliasCtrl_OffsetNoise';
        main_layout = {'brightzone_pos_angle',        180, ...
                         'quietzone_pos_angle',         0, ...
                         'brightzone_source_angle',     15};
        masker_layout = {'brightzone_pos_angle',        0, ...
                         'quietzone_pos_angle',         180, ...
                         'brightzone_source_angle',     15};
    elseif scheme == 9
        % % Setup and Privacy Scheme 9
        Masker_Type = 'ZoneWeightMask_AliasCtrl_StereoNoise';
        main_layout = {'brightzone_pos_angle',        180, ...
                         'quietzone_pos_angle',         0, ...
                         'brightzone_source_angle',     15};
        masker_layout = {'brightzone_pos_angle',        0, ...
                         'quietzone_pos_angle',         180, ...
                         'brightzone_source_angle',     30};
                     
                     
    elseif scheme == 10
        % % Setup and Privacy Scheme 10
        % Multizone vs PAL Privacy Scheme Part 1 - Speech
        Masker_Type = 'NoMask';
        Zone_Weights = 1e4;
        Noise_Mask_Levels = -inf;
        main_layout = { ...
            'brightzone_pos_angle',        90, ...
            'quietzone_pos_angle',         -90, ...
            'brightzone_source_angle',     0, ...
            'brightzone_source_type',      'pw'};
        masker_layout = {};
        loudspeaker_layout = { ...
            'angleto_firstloudspeaker',      90, ...
            'numberof_loudspeakers',         24, ...
            'loudspeaker_model',             'Genelec 8010A', ...
            'loudspeaker_radius',            1.5, ...
            'loudspeaker_spacing',           [], ...
            'speaker_array_type',            array_type, ...
            'brightzone_source_dist',        x_, ...
            other{:}};
        main_loudspeaker_layout = loudspeaker_layout;
        
    elseif scheme == 10.1
        % % Setup and Privacy Scheme 10
        % Multizone vs PAL Privacy Scheme Part 2 - Multizone Masker
        Masker_Type = 'ZoneWeightMaskerAliasCtrl';
        Zone_Weights = 1e4;
        Noise_Mask_Levels = Noise_Mask_Levels_;
        main_layout = {};
        masker_layout = { ...
            'brightzone_pos_angle',        -90, ...
            'quietzone_pos_angle',         90, ...
            'brightzone_source_angle',     180, ...
            'brightzone_source_type',      'ps'};
        loudspeaker_layout = { ...
            'angleto_firstloudspeaker',      90, ...
            'numberof_loudspeakers',         24, ...
            'loudspeaker_model',             'Genelec 8010A', ...
            'loudspeaker_radius',            1.5, ...
            'loudspeaker_spacing',           [], ...
            'speaker_array_type',            array_type, ...
            'brightzone_source_dist',        x_, ...
            other{:}};
        main_loudspeaker_layout = loudspeaker_layout;
        
    elseif scheme == 10.2
        % % Setup and Privacy Scheme 10
        % Multizone vs PAL Privacy Scheme Part 3 - Parametric Masker
        Masker_Type = 'ParametricMasker';
        Zone_Weights = 1;
        Noise_Mask_Levels = Noise_Mask_Levels_;
        main_layout = {};
        masker_layout = { ...
            'brightzone_pos_angle',        -90, ...
            'quietzone_pos_angle',         90, ...
            'brightzone_source_angle',     180, ...
            'brightzone_source_type',      'ps'};
        loudspeaker_layout = { ...
            'angleto_firstloudspeaker',     th/pi*180, ...
            'loudspeaker_radius',           x_, ...
            'numberof_loudspeakers',        1, ...
            'loudspeaker_model',            'Parametric', ...
            'loudspeaker_spacing',          0.01, ...
            'speaker_array_type',           'line', ...
            'brightzone_source_dist',        x_, ...
            other{:}};
        main_loudspeaker_layout = loudspeaker_layout;
        
    elseif scheme == 10.3
        % % Setup and Privacy Scheme 10
        % Multizone vs PAL Privacy Scheme Part 4 - Parametric Masker HPF
        Masker_Type = 'ParametricMaskerAliasCtrlHPF';
        Zone_Weights = 1;
        Noise_Mask_Levels = Noise_Mask_Levels_;
        main_loudspeaker_layout = { ...
            'angleto_firstloudspeaker',      90, ...
            'numberof_loudspeakers',         24, ...
            'loudspeaker_model',             'Genelec 8010A', ...
            'loudspeaker_radius',            1.5, ...
            'loudspeaker_spacing',           [], ...
            'speaker_array_type',            array_type, ...
            'brightzone_source_dist',        x_, ...
            other{:}};
        masker_layout = { ...
            'brightzone_pos_angle',        -90, ...
            'quietzone_pos_angle',         90, ...
            'brightzone_source_angle',     180, ...
            'brightzone_source_type',      'ps'};
        main_layout = masker_layout;
        loudspeaker_layout = { ...
            'angleto_firstloudspeaker',     th/pi*180, ...
            'loudspeaker_radius',           x_, ...
            'numberof_loudspeakers',        1, ...
            'loudspeaker_model',            'Parametric', ...
            'loudspeaker_spacing',          0.01, ...
            'speaker_array_type',           'line', ...
            'brightzone_source_dist',        x_, ...
            other{:}};
                     
    end
    
    Main_Setup = Speaker_Setup.createSetup({ main_layout{:}, main_loudspeaker_layout{:}});    
    Masker_Setup = Speaker_Setup.createSetup({ masker_layout{:}, loudspeaker_layout{:}});
    
    Broadband_Tools.Generate_Loudspeaker_Signals_batchfunc(Zone_Weights, Noise_Mask_Levels, Masker_Type, Main_Setup, Masker_Setup);
    
end