%clc;
clear;
%close all;
tic;

%%
results_contrastdb = [];
results_perc = [];
for spkr = 1:2
    freqs = (10.0^3) * ((2.0) .^ ([-8:9]./3)); %Third octave
    for f = 1:length(freqs)
        
        %%
        room_width = 3.200; % metres
        rad = ( room_width - 2*0.115 - 2*0.085 ) / 2; % metres
        
        % speech_layout = {'brightzone_pos_angle',        180, ...
        %                  'quietzone_pos_angle',         0, ...
        %                  'brightzone_source_angle',     14.5};
        % masker_layout = {'brightzone_pos_angle',        0, ...
        %                  'quietzone_pos_angle',         180, ...
        %                  'brightzone_source_angle',     0};
        
        speech_layout = {'brightzone_pos_angle',        90, ...
            'quietzone_pos_angle',         -90, ...
            'brightzone_source_angle',     0};
        masker_layout = {'brightzone_pos_angle',        -90, ...
            'quietzone_pos_angle',         90, ...
            'brightzone_source_angle',     0};
        
        if spkr ==1
            masker = {'angleto_firstloudspeaker',      90, ...
                'numberof_loudspeakers',         24, ...
                'loudspeaker_model',             'Genelec 8010A'};
        elseif spkr == 2
            %parametric
            th = atan2(-0.6,-1.5);
            masker = {'angleto_firstloudspeaker',     th/pi*180, ...
                'numberof_loudspeakers',        1, ...
                'loudspeaker_model',            'Parametric'};
        end
        setup = Speaker_Setup.createSetup({...
            'frequency',                    freqs(f), ...
            masker_layout{:}, ...
            masker{:}, ...
            'resolution',                   100, ... % Minimum resolution of approx 50 for 8kHz signal to satisfy nyquist theorem. We choose 100 for good measure.
            'reproduction_radius',          1.0, ...
            'bright_weight',                1.0, ...
            'quiet_weight',                 0, ...
            'unattended_weight',            0.05, ...
            'brightzone_radius',            0.3, ...
            'brightzone_pos_distance',      0.6, ...
            'quietzone_radius',             0.3, ...
            'quietzone_pos_distance',       0.6, ...
            'maximum_frequency',            8000, ...
            'loudspeaker_radius',            1.5, ...
            'angleof_loudspeakerarc',       180 , ...
            'loudspeaker_object',           Parametric_Synthesis.parametric_soundfield, ...
            'angleof_loudspeakerarrcentre', 180, ...
            'loudspeaker_spacing',          0.01, ...
            'speaker_array_type',           'line'});
        
        %%
        setup.Multizone_Soundfield = setup.Multizone_Soundfield.createSoundfield('DEBUG');
        
        setup = setup.calc_Loudspeaker_Weights();
        setup = setup.reproduceSoundfield('SAMPLES_ONLY');                
        
        results_perc(spkr,f)       = (setup.Bright_Sample - setup.Quiet_Sample)*100;
        results_contrastdb(spkr,f) = mag2db(setup.Acoustic_Contrast);
        %%
    end
end
%%
figure(1);
plot(freqs,results_perc');
xlim([1e2 1e4]);
grid minor
set(gca,'XScale','log');
title('Multizone vs Parametic - Percent Difference  (Third Octave)');
legend({'Regular Multizone';'Parametric Multizone'});
ylabel('Percent Level Difference (%)');
xlabel('Frequency (Hz)');

figure(2);
plot(freqs,results_contrastdb');
xlim([1e2 1e4]);
grid minor
set(gca,'XScale','log');
title('Multizone vs Parametic - Acoustic Contrast  (Third Octave)');
legend({'Regular Multizone';'Parametric Multizone'});
ylabel('Acoustic Contrast (dB)');
xlabel('Frequency (Hz)');

%%
tEnd = toc;
fprintf('Execution time: %dmin(s) %fsec(s)\n', floor(tEnd/60), rem(tEnd,60)); %Time taken to execute this script