%clc;
clear;
%close all;
tic;

%%
results_contrastdb = [];
results_perc = [];
for spkr = 1:2
    freqs = (10.0^3) * ((2.0) .^ ([-8:9]./3)); %Third octave
    %freqs = logspace(log10(150),log10(8000),100);
    for f = 1:length(freqs)
        
        %%
        room_width = 3.200; % metres
        rad = ( room_width - 2*0.115 - 2*0.085 ) / 2; % metres
        
        % speech_layout = {'brightzone_pos_angle',        180, ...
        %                  'quietzone_pos_angle',         0, ...
        %                  'brightzone_source_angle',     14.5};
        % masker_layout = {'brightzone_pos_angle',        0, ...
        %                  'quietzone_pos_angle',         180, ...
        %                  'brightzone_source_angle',     0};
        
        speech_layout = {'brightzone_pos_angle',        90, ...
            'quietzone_pos_angle',         -90, ...
            'brightzone_source_angle',     0};
        masker_layout = { ...
            'brightzone_pos_angle',        -90, ...
            'quietzone_pos_angle',         90, ...
            'brightzone_source_angle',     180, ...
            'brightzone_source_type',      'ps'};
        
        array_type = 'circle';
        spkr_radius = 1.3;
        
        if strcmp(array_type, 'circle')
            [x,y] = pol2cart(-90/180*pi, 0.6);
            x_ = sqrt(spkr_radius^2-y^2);
            th_c = atan2(y,-x_);
            th = th_c;
            spkr_spacing = []; %Auto-calculate spacing
        elseif strcmp(array_type, 'line')
            x_=spkr_radius;
            th_c = 180;
            th = atan2(-0.6,-spkr_radius);
            spkr_spacing = 0.001; %1mm spacing between adjacent loudspeakers
        end
        if spkr ==1
            N_spkrs = 24;
            masker = { ...
                'angleto_firstloudspeaker',      90, ...
                'angleof_loudspeakerarc',        180 * N_spkrs/(N_spkrs-1) , ...
                'numberof_loudspeakers',         N_spkrs, ...
                'loudspeaker_model',             'Genelec 8010A', ...
                'loudspeaker_radius',            spkr_radius, ...
                'loudspeaker_spacing',           spkr_spacing, ...
                'speaker_array_type',            array_type, ...
                'brightzone_source_dist',        x_};
        elseif spkr == 2
%             %parametric
%             masker = {  ...
%                 'angleto_firstloudspeaker',     th/pi*180, ...
%                 'loudspeaker_radius',           x_, ...
%                 'numberof_loudspeakers',        1, ...
%                 'loudspeaker_model',            'Parametric', ...
%                 'loudspeaker_spacing',          0.01, ...
%                 'speaker_array_type',           'line', ...
%                 'brightzone_source_dist',        x_};
        masker_layout = { ...
            'brightzone_pos_angle',        -90, ...
            'quietzone_pos_angle',         90, ...
            'brightzone_source_angle',      0, ...
            'brightzone_source_type',      'pw'};
            N_spkrs = 24;
            masker = { ...
                'angleto_firstloudspeaker',      90, ...
                'angleof_loudspeakerarc',        180 * N_spkrs/(N_spkrs-1) , ...
                'numberof_loudspeakers',         N_spkrs, ...
                'loudspeaker_model',             'Genelec 8010A', ...
                'loudspeaker_radius',            spkr_radius, ...
                'loudspeaker_spacing',           spkr_spacing, ...
                'speaker_array_type',            array_type, ...
                'brightzone_source_dist',        x_};
        end
        setup = Speaker_Setup.createSetup({...
            'frequency',                    freqs(f), ...
            masker_layout{:}, ...
            masker{:}, ...
            'resolution',                   100, ... % Minimum resolution of approx 50 for 8kHz signal to satisfy nyquist theorem. We choose 100 for good measure.
            'reproduction_radius',          1.0, ...
            'bright_weight',                1.0, ...
            'quiet_weight',                 0, ...
            'unattended_weight',            0.05, ...
            'brightzone_radius',            0.3, ...
            'brightzone_pos_distance',      0.6, ...
            'quietzone_radius',             0.3, ...
            'quietzone_pos_distance',       0.6, ...
            'maximum_frequency',            8000, ...
            'angleof_loudspeakerarrcentre', 180, ...
            'loudspeaker_object',           Parametric_Synthesis.parametric_soundfield });
        
        %%
        setup.Multizone_Soundfield = setup.Multizone_Soundfield.createSoundfield('DEBUG');
        
        setup = setup.calc_Loudspeaker_Weights();
        setup = setup.reproduceSoundfield('SAMPLES_ONLY');
        
        results_perc(spkr,f)       = (setup.Bright_Sample - setup.Quiet_Sample)*100;
        results_contrastdb(spkr,f) = mag2db(setup.Acoustic_Contrast);
        %%
    end
end
%%
[~,ind]=max(results_perc);
ind1 = logical(mod(ind,2));
ind2 = [~ind1(2:end) true];
figure(1);
plot(freqs,results_perc'); hold on; set(gca,'ColorOrderIndex',1);
% plot(freqs(ind1),results_perc(1,ind1),'LineWidth',3); set(gca,'ColorOrderIndex',2);
% plot(freqs(ind2),results_perc(2,ind2),'LineWidth',3); hold off;
xlim([1e2 1e4]);
grid minor
set(gca,'XScale','log');
title('Multizone vs Parametic - Percent Difference  (Third Octave)');
legend({'Orthogonal Basis Expansion Multizone';'Parametric Multizone'},'location','southwest');
ylabel('Percent Level Difference (%)');
xlabel('Frequency (Hz)');

[~,ind]=max(results_contrastdb);
ind1 = logical(mod(ind,2));
ind2 = [~ind1(2:end) true];
figure(2);
plot(freqs,results_contrastdb'); hold on; set(gca,'ColorOrderIndex',1);
% plot(freqs(ind1),results_contrastdb(1,ind1),'LineWidth',3); set(gca,'ColorOrderIndex',2);
% plot(freqs(ind2),results_contrastdb(2,ind2),'LineWidth',3); hold off;
xlim([1e2 1e4]);
grid minor
set(gca,'XScale','log');
title('Multizone vs Parametic - Acoustic Contrast  (Third Octave)');
legend({'Orthogonal Basis Expansion Multizone';'Parametric Multizone'},'location','southwest');
ylabel('Acoustic Contrast (dB)');
xlabel('Frequency (Hz)');

%%
tEnd = toc;
fprintf('Execution time: %dmin(s) %fsec(s)\n', floor(tEnd/60), rem(tEnd,60)); %Time taken to execute this script